FROM nginx
COPY ./dist/apps/client/* /usr/share/nginx/html

RUN mkdir -p /app/scripts
RUN mkdir -p /app/html
RUN mkdir -p /app/ssl

# copy web server config
WORKDIR /etc/nginx
COPY tools/docker-web-server/nginx.conf ./conf.d/default.conf

WORKDIR /app
COPY tools/docker-web-server/replace_variables.sh ./scripts
COPY tools/docker-web-server/start.sh ./scripts

# copy app files to container
WORKDIR /app/html
COPY dist/apps/client .

CMD ["/bin/bash", "/app/scripts/start.sh", "/app/html"]