# Description: Dockerfile for server

FROM node:20-slim

RUN mkdir -p /server

WORKDIR /server

# copy project package files
COPY package.json .
COPY yarn.lock .

# copy yarn configuration files
COPY .yarn ./.yarn
COPY .yarnrc.yml .

# install dependencies
RUN yarn install

# copy server files
COPY dist/apps/server .

# expose port 3000
EXPOSE 3000

# making sure container starts from the right folder
WORKDIR /server

# run server
ENTRYPOINT ["node", "main.js"]
