version: '3.9'
name: flltms

services:
  server:
    restart: always
    image: fllsk/tms-server:latest
    environment:
      # the environment variables are used by a service that automaically manages letsencrypt certificates
      - VIRTUAL_HOST=api.flltms.spv99.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.flltms.spv99.com
      - PORT=3000

    networks:
      - proxy-net
    expose:
      - 3000

  client:
    restart: always
    image: fllsk/tms-client:latest
    depends_on:
      - server
    environment:
      - VIRTUAL_HOST=flltms.spv99.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=flltms.spv99.com

    expose:
      - 80
    networks:
      - proxy-net

networks:
  proxy-net:
    name: proxy-net
    external: true
