version: '3.9'
name: flltms

services:
  server:
    restart: always
    image: fllsk/tms-server:latest
    environment:
      # the environment variables are used by a service that automaically manages letsencrypt certificates
      - VIRTUAL_HOST=api.flltms.spv99.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.flltms.spv99.com
      - PORT=3000

      - APP_CLIENT_ROOT_URL=${APP_CLIENT_ROOT_URL}
      - APP_EMAIL_FROM=${APP_EMAIL_FROM}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_LOGO_URL=${APP_LOGO_URL}
      - APP_MONGODB=${APP_MONGODB}
      - APP_GRAPHQL_SCHEMA_PATH=${APP_GRAPHQL_SCHEMA_PATH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=${DEBUG}
      - NODE_ENV=${NODE_ENV}
      - NX_SF_API_URL=${NX_SF_API_URL}
      - SF_AUTH_API_KEY=${SF_AUTH_API_KEY}
      - SF_AUTH_COMPANY_ID=${SF_AUTH_COMPANY_ID}
      - SF_AUTH_EMAIL=${SF_AUTH_EMAIL}
      - SF_AUTH_MODULE=${SF_AUTH_MODULE}
      - SF_PAYMENT_KEY=${SF_PAYMENT_KEY}
      - SUPERADMIN_USERNAME=${SUPERADMIN_USERNAME}
      - TEAMS_ADMIN_EMAIL=${TEAMS_ADMIN_EMAIL}

    networks:
      - proxy-net
    expose:
      - 3000

  client:
    restart: always
    image: fllsk/tms-client:latest
    depends_on:
      - server
    environment:
      - VIRTUAL_HOST=tms.fll.sk
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=tms.fll.sk

    expose:
      - 80
    networks:
      - proxy-net

networks:
  proxy-net:
    name: proxy-net
    external: true
