# replacing __redirects file with this configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  [context.production.environment]
    NX_API_URL = "https://api.flltms.spv99.com"
    NX_SF_API_URL="https://moja.superfaktura.sk"

